### ISSUE TITLE
code error main.py

### ISSUE THREAD

**Issue by zjw511** [wilile26811249/ViTGAN#5]
`    train(netG_s, netG, netD, optimizer_g, optimizer_d, data_loader, device)`
in main.py 125 line
should be 
`    train(netG, netG_s, netD, optimizer_g, optimizer_d, data_loader, device)`
because you train netG in optim,but in `def train` you train netG_s

**Comment by wilile26811249** [comment]
@Mmhmmmmm  Yes, you are right. I have already update.
